#ifndef GENERATED_ASN1SCC_dataview_uniq_H
#define GENERATED_ASN1SCC_dataview_uniq_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccSint asn1SccMyInteger;


#define ERR_MYINTEGER		1  /*(-1024..1024)*/
flag asn1SccMyInteger_IsConstraintValid(const asn1SccMyInteger* pVal, int* pErrCode);

void asn1SccMyInteger_Initialize(asn1SccMyInteger* pVal);

#define ERR_UPER_ENCODE_MYINTEGER		2  /**/
#define asn1SccMyInteger_REQUIRED_BYTES_FOR_ENCODING       2
#define asn1SccMyInteger_REQUIRED_BITS_FOR_ENCODING        12

flag asn1SccMyInteger_Encode(const asn1SccMyInteger* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_MYINTEGER		3  /**/
flag asn1SccMyInteger_Decode(asn1SccMyInteger* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccMyBooleanResult;


#define ERR_MYBOOLEANRESULT		6  /**/
flag asn1SccMyBooleanResult_IsConstraintValid(const asn1SccMyBooleanResult* pVal, int* pErrCode);

void asn1SccMyBooleanResult_Initialize(asn1SccMyBooleanResult* pVal);

#define ERR_UPER_ENCODE_MYBOOLEANRESULT		7  /**/
#define asn1SccMyBooleanResult_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccMyBooleanResult_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccMyBooleanResult_Encode(const asn1SccMyBooleanResult* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_MYBOOLEANRESULT		8  /**/
flag asn1SccMyBooleanResult_Decode(asn1SccMyBooleanResult* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccBinaryBooleanTestParam --------------------------------------------*/
typedef enum {
    BinaryBooleanTestParam_oper_o_and = 0,
    BinaryBooleanTestParam_oper_o_or = 1,
    BinaryBooleanTestParam_oper_o_xor = 2,
    BinaryBooleanTestParam_oper_o_implies = 3
} asn1SccBinaryBooleanTestParam_oper;

// please use the following macros to avoid breaking code.
#define asn1SccBinaryBooleanTestParam_oper_o_and BinaryBooleanTestParam_oper_o_and
#define asn1SccBinaryBooleanTestParam_oper_o_or BinaryBooleanTestParam_oper_o_or
#define asn1SccBinaryBooleanTestParam_oper_o_xor BinaryBooleanTestParam_oper_o_xor
#define asn1SccBinaryBooleanTestParam_oper_o_implies BinaryBooleanTestParam_oper_o_implies
typedef struct {
    asn1SccBinaryBooleanTestParam_oper oper;
    asn1SccMyBooleanResult left;
    asn1SccMyBooleanResult right;

} asn1SccBinaryBooleanTestParam;

#define ERR_BINARYBOOLEANTESTPARAM_OPER		11  /*o-and | o-or | o-xor | o-implies*/
flag asn1SccBinaryBooleanTestParam_oper_IsConstraintValid(const asn1SccBinaryBooleanTestParam_oper* pVal, int* pErrCode);

#define ERR_BINARYBOOLEANTESTPARAM		36  /**/
#define ERR_BINARYBOOLEANTESTPARAM_LEFT_2		21  /**/
#define ERR_BINARYBOOLEANTESTPARAM_RIGHT_2		31  /**/
flag asn1SccBinaryBooleanTestParam_IsConstraintValid(const asn1SccBinaryBooleanTestParam* pVal, int* pErrCode);

void asn1SccBinaryBooleanTestParam_oper_Initialize(asn1SccBinaryBooleanTestParam_oper* pVal);
void asn1SccBinaryBooleanTestParam_Initialize(asn1SccBinaryBooleanTestParam* pVal);

#define ERR_UPER_ENCODE_BINARYBOOLEANTESTPARAM		37  /**/
#define ERR_UPER_ENCODE_BINARYBOOLEANTESTPARAM_OPER		12  /**/
#define ERR_UPER_ENCODE_BINARYBOOLEANTESTPARAM_LEFT_2		22  /**/
#define ERR_UPER_ENCODE_BINARYBOOLEANTESTPARAM_RIGHT_2		32  /**/
#define asn1SccBinaryBooleanTestParam_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccBinaryBooleanTestParam_REQUIRED_BITS_FOR_ENCODING        4

flag asn1SccBinaryBooleanTestParam_Encode(const asn1SccBinaryBooleanTestParam* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BINARYBOOLEANTESTPARAM		38  /**/
#define ERR_UPER_DECODE_BINARYBOOLEANTESTPARAM_OPER		13  /**/
#define ERR_UPER_DECODE_BINARYBOOLEANTESTPARAM_LEFT_2		23  /**/
#define ERR_UPER_DECODE_BINARYBOOLEANTESTPARAM_RIGHT_2		33  /**/
flag asn1SccBinaryBooleanTestParam_Decode(asn1SccBinaryBooleanTestParam* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccUnaryBooleanTestParam --------------------------------------------*/
typedef struct {
    asn1SccMyBooleanResult expr;

} asn1SccUnaryBooleanTestParam;

#define ERR_UNARYBOOLEANTESTPARAM		51  /**/
#define ERR_UNARYBOOLEANTESTPARAM_EXPR_2		46  /**/
flag asn1SccUnaryBooleanTestParam_IsConstraintValid(const asn1SccUnaryBooleanTestParam* pVal, int* pErrCode);

void asn1SccUnaryBooleanTestParam_Initialize(asn1SccUnaryBooleanTestParam* pVal);

#define ERR_UPER_ENCODE_UNARYBOOLEANTESTPARAM		52  /**/
#define ERR_UPER_ENCODE_UNARYBOOLEANTESTPARAM_EXPR_2		47  /**/
#define asn1SccUnaryBooleanTestParam_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccUnaryBooleanTestParam_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccUnaryBooleanTestParam_Encode(const asn1SccUnaryBooleanTestParam* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_UNARYBOOLEANTESTPARAM		53  /**/
#define ERR_UPER_DECODE_UNARYBOOLEANTESTPARAM_EXPR_2		48  /**/
flag asn1SccUnaryBooleanTestParam_Decode(asn1SccUnaryBooleanTestParam* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int32;


#define ERR_T_INT32		56  /*(-2147483648 .. 2147483647)*/
flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode);

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal);

#define ERR_UPER_ENCODE_T_INT32		57  /**/
#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT32		58  /**/
flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt32;


#define ERR_T_UINT32		61  /*(0 .. 4294967295)*/
flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode);

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal);

#define ERR_UPER_ENCODE_T_UINT32		62  /**/
#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT32		63  /**/
flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Runtime_Error --------------------------------------------*/

typedef enum {
    T_Runtime_Error_NONE,
    T_Runtime_Error_noerror_PRESENT,
    T_Runtime_Error_encodeerror_PRESENT,
    T_Runtime_Error_decodeerror_PRESENT
} asn1SccT_Runtime_Error_selection;

typedef union {
    asn1SccT_UInt32 noerror;
    asn1SccT_Int32 encodeerror;
    asn1SccT_Int32 decodeerror;
} asn1SccT_Runtime_Error_unchecked_union;

typedef struct {
    asn1SccT_Runtime_Error_selection kind;

    asn1SccT_Runtime_Error_unchecked_union u;
} asn1SccT_Runtime_Error;

#define ERR_T_RUNTIME_ERROR		116  /**/
#define ERR_T_RUNTIME_ERROR_NOERROR_2		91  /**/
#define ERR_T_RUNTIME_ERROR_ENCODEERROR_2		101  /**/
#define ERR_T_RUNTIME_ERROR_DECODEERROR_2		111  /**/
flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode);

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal);

#define ERR_UPER_ENCODE_T_RUNTIME_ERROR		117  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_NOERROR_2		92  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		102  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		112  /**/
#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ENCODING        34

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_RUNTIME_ERROR		118  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_NOERROR_2		93  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		103  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		113  /**/
flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int8;


#define ERR_T_INT8		66  /*(-128 .. 127)*/
flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode);

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal);

#define ERR_UPER_ENCODE_T_INT8		67  /**/
#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT8		68  /**/
flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt8;


#define ERR_T_UINT8		71  /*(0 .. 255)*/
flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode);

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal);

#define ERR_UPER_ENCODE_T_UINT8		72  /**/
#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT8		73  /**/
flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccT_Boolean;


#define ERR_T_BOOLEAN		76  /**/
flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode);

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal);

#define ERR_UPER_ENCODE_T_BOOLEAN		77  /**/
#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_BOOLEAN		78  /**/
flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Null_Record --------------------------------------------*/
typedef struct {

} asn1SccT_Null_Record;

#define ERR_T_NULL_RECORD		81  /**/
flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode);

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ENCODING        0

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccPID_Range;


#define ERR_PID_RANGE		121  /*(0..4)*/
flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode);

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal);

#define ERR_UPER_ENCODE_PID_RANGE		122  /**/
#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ENCODING        3

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID_RANGE		123  /**/
flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    PID_taste_user_interface = 0,
    PID_timer_manager = 1,
    PID_actuator = 2,
    PID_controller = 3,
    PID_env = 4
} asn1SccPID;

// please use the following macros to avoid breaking code.
#define asn1SccPID_taste_user_interface PID_taste_user_interface
#define asn1SccPID_timer_manager PID_timer_manager
#define asn1SccPID_actuator PID_actuator
#define asn1SccPID_controller PID_controller
#define asn1SccPID_env PID_env

#define ERR_PID		126  /*taste-user-interface | timer-manager | actuator | controller | env*/
flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode);

void asn1SccPID_Initialize(asn1SccPID* pVal);

#define ERR_UPER_ENCODE_PID		127  /**/
#define asn1SccPID_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ENCODING        3

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID		128  /**/
flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
