#define asn1SccMyInteger_REQUIRED_BYTES_FOR_ENCODING       2
#define asn1SccMySequenceDataType_REQUIRED_BYTES_FOR_ENCODING       10
#define asn1SccMyChoiceDataType_REQUIRED_BYTES_FOR_ENCODING       2
#define asn1SccMyArrayDataType_REQUIRED_BYTES_FOR_ENCODING       6
#define asn1SccMySequenceWithOptionalsDataType_REQUIRED_BYTES_FOR_ENCODING       6
#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ENCODING       5
#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ENCODING       0
#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_REQUIRED_BYTES_FOR_ENCODING       1
