.PHONY: \
	simplesignals \
	parameterless \
	simpleparameters \
	flowcontrol \
	stop_condition_eventually \
	stop_condition_never_filter_out \
	stop_condition_present \
	stop_condition_length \
	stop_condition_exist \
	asn1_sequence \
	asn1_sequenceof \
	asn1_sequenceof_fixed \
	asn1_octetstring \
	asn1_octetstring_fixed \
	asn1_choice \
	integer_expressions \
	relation_expressions \
	boolean_expressions \
	continuous_signal_simple \
	function_types

check: \
	simplesignals \
	parameterless \
	simpleparameters \
	flowcontrol \
	stop_condition_eventually \
	stop_condition_never_filter_out \
	stop_condition_present \
	stop_condition_length \
	stop_condition_exist \
	asn1_sequence \
	asn1_sequenceof \
	asn1_sequenceof_fixed \
	asn1_octetstring \
	asn1_octetstring_fixed \
	asn1_choice \
	integer_expressions \
	relation_expressions \
	boolean_expressions \
	continuous_signal_simple \
	function_types

simplesignals:
	${MAKE} -C $@ check

parameterless:
	${MAKE} -C $@ check

simpleparameters:
	${MAKE} -C $@ check

flowcontrol:
	${MAKE} -C $@ check

stop_condition_eventually:
	${MAKE} -C $@ check

stop_condition_never_filter_out:
	${MAKE} -C $@ check

stop_condition_present:
	${MAKE} -C $@ check

stop_condition_length:
	${MAKE} -C $@ check

stop_condition_exist:
	${MAKE} -C $@ check

asn1_sequence:
	${MAKE} -C $@ check

asn1_sequenceof:
	${MAKE} -C $@ check

asn1_sequenceof_fixed:
	${MAKE} -C $@ check

asn1_octetstring:
	${MAKE} -C $@ check

asn1_octetstring_fixed:
	${MAKE} -C $@ check

asn1_choice:
	${MAKE} -C $@ check

integer_expressions:
	${MAKE} -C $@ check

relation_expressions:
	${MAKE} -C $@ check

boolean_expressions:
	${MAKE} -C $@ check

continuous_signal_simple:
	${MAKE} -C $@ check

function_types:
	${MAKE} -C $@ check
