model-check: InterfaceView.aadl DeploymentView.aadl DataView.aadl
	$(KAZOO) -gw --glue -t MOCHECK
	$(MAKE) -C work model-check

create-obs: work/modelchecking/properties work/modelchecking
	mkdir -p work/modelchecking/properties/$(NAME)
	make -C work obs-skeleton NAME=$(NAME)

create-msc: work/modelchecking/properties work/modelchecking
	mkdir -p work/modelchecking/properties/$(NAME)
	make -C work msc-skeleton NAME=$(NAME)

create-bsc: work/modelchecking/properties work/modelchecking
	mkdir -p work/modelchecking/properties/$(NAME)
	make -C work bsc-skeleton NAME=$(NAME)

work/modelchecking/properties:
	mkdir -p work/modelchecking/properties

work/modelchecking:
	mkdir -p work/modelchecking

create-subtype: work/modelchecking/subtypes work/modelchecking
	find work/ -path work/binaries -prune -o -name subtype_*.asn -exec cat {} \; >  work/modelchecking/subtypes/$(NAME).asn
	cd work/modelchecking/subtypes && kate $(NAME).asn

work/modelchecking/subtypes:
	mkdir -p work/modelchecking/subtypes

