#ifndef GENERATED_ASN1SCC_dataview_uniq_H
#define GENERATED_ASN1SCC_dataview_uniq_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint asn1SccMyInteger;


#define ERR_MYINTEGER		1  /*(0 .. 10000)*/
flag asn1SccMyInteger_IsConstraintValid(const asn1SccMyInteger* pVal, int* pErrCode);

void asn1SccMyInteger_Initialize(asn1SccMyInteger* pVal);

#define ERR_UPER_ENCODE_MYINTEGER		2  /**/
#define asn1SccMyInteger_REQUIRED_BYTES_FOR_ENCODING       2
#define asn1SccMyInteger_REQUIRED_BITS_FOR_ENCODING        14

flag asn1SccMyInteger_Encode(const asn1SccMyInteger* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_MYINTEGER		3  /**/
flag asn1SccMyInteger_Decode(asn1SccMyInteger* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccALPHA_EMPTY --------------------------------------------*/
typedef struct {

} asn1SccALPHA_EMPTY;

#define ERR_ALPHA_EMPTY		6  /**/
flag asn1SccALPHA_EMPTY_IsConstraintValid(const asn1SccALPHA_EMPTY* pVal, int* pErrCode);

void asn1SccALPHA_EMPTY_Initialize(asn1SccALPHA_EMPTY* pVal);

#define asn1SccALPHA_EMPTY_REQUIRED_BYTES_FOR_ENCODING       0
#define asn1SccALPHA_EMPTY_REQUIRED_BITS_FOR_ENCODING        0

flag asn1SccALPHA_EMPTY_Encode(const asn1SccALPHA_EMPTY* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccALPHA_EMPTY_Decode(asn1SccALPHA_EMPTY* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccALPHA_MEMORY_BASE --------------------------------------------*/

typedef enum {
    ALPHA_MEMORY_BASE_NONE,
    ALPHA_MEMORY_BASE_ram_memory_PRESENT,
    ALPHA_MEMORY_BASE_db_memory_PRESENT,
    ALPHA_MEMORY_BASE_spare_memory_PRESENT
} asn1SccALPHA_MEMORY_BASE_selection;

typedef union {
    asn1SccALPHA_EMPTY ram_memory;
    asn1SccMyInteger db_memory;
    asn1SccMyInteger spare_memory;
} asn1SccALPHA_MEMORY_BASE_unchecked_union;

typedef struct {
    asn1SccALPHA_MEMORY_BASE_selection kind;

    asn1SccALPHA_MEMORY_BASE_unchecked_union u;
} asn1SccALPHA_MEMORY_BASE;

#define ERR_ALPHA_MEMORY_BASE		46  /**/
#define ERR_ALPHA_MEMORY_BASE_RAM_MEMORY_2		21  /**/
#define ERR_ALPHA_MEMORY_BASE_DB_MEMORY_2		31  /**/
#define ERR_ALPHA_MEMORY_BASE_SPARE_MEMORY_2		41  /**/
flag asn1SccALPHA_MEMORY_BASE_IsConstraintValid(const asn1SccALPHA_MEMORY_BASE* pVal, int* pErrCode);

void asn1SccALPHA_MEMORY_BASE_Initialize(asn1SccALPHA_MEMORY_BASE* pVal);

#define ERR_UPER_ENCODE_ALPHA_MEMORY_BASE		47  /**/
#define ERR_UPER_ENCODE_ALPHA_MEMORY_BASE_DB_MEMORY_2		32  /**/
#define ERR_UPER_ENCODE_ALPHA_MEMORY_BASE_SPARE_MEMORY_2		42  /**/
#define asn1SccALPHA_MEMORY_BASE_REQUIRED_BYTES_FOR_ENCODING       2
#define asn1SccALPHA_MEMORY_BASE_REQUIRED_BITS_FOR_ENCODING        16

flag asn1SccALPHA_MEMORY_BASE_Encode(const asn1SccALPHA_MEMORY_BASE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_ALPHA_MEMORY_BASE		48  /**/
#define ERR_UPER_DECODE_ALPHA_MEMORY_BASE_DB_MEMORY_2		33  /**/
#define ERR_UPER_DECODE_ALPHA_MEMORY_BASE_SPARE_MEMORY_2		43  /**/
flag asn1SccALPHA_MEMORY_BASE_Decode(asn1SccALPHA_MEMORY_BASE* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    ALPHA_MEMORY_IDENTIFIER_ram_memory = 1,
    ALPHA_MEMORY_IDENTIFIER_db_memory = 2,
    ALPHA_MEMORY_IDENTIFIER_spare_memory = 100
} asn1SccALPHA_MEMORY_IDENTIFIER;

// please use the following macros to avoid breaking code.
#define asn1SccALPHA_MEMORY_IDENTIFIER_ram_memory ALPHA_MEMORY_IDENTIFIER_ram_memory
#define asn1SccALPHA_MEMORY_IDENTIFIER_db_memory ALPHA_MEMORY_IDENTIFIER_db_memory
#define asn1SccALPHA_MEMORY_IDENTIFIER_spare_memory ALPHA_MEMORY_IDENTIFIER_spare_memory

#define ERR_ALPHA_MEMORY_IDENTIFIER		11  /*ram-memory | db-memory | spare-memory*/
flag asn1SccALPHA_MEMORY_IDENTIFIER_IsConstraintValid(const asn1SccALPHA_MEMORY_IDENTIFIER* pVal, int* pErrCode);

void asn1SccALPHA_MEMORY_IDENTIFIER_Initialize(asn1SccALPHA_MEMORY_IDENTIFIER* pVal);

#define ERR_UPER_ENCODE_ALPHA_MEMORY_IDENTIFIER		12  /**/
#define asn1SccALPHA_MEMORY_IDENTIFIER_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccALPHA_MEMORY_IDENTIFIER_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccALPHA_MEMORY_IDENTIFIER_Encode(const asn1SccALPHA_MEMORY_IDENTIFIER* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_ALPHA_MEMORY_IDENTIFIER		13  /**/
flag asn1SccALPHA_MEMORY_IDENTIFIER_Decode(asn1SccALPHA_MEMORY_IDENTIFIER* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int32;


#define ERR_T_INT32		51  /*(-2147483648 .. 2147483647)*/
flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode);

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal);

#define ERR_UPER_ENCODE_T_INT32		52  /**/
#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT32		53  /**/
flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt32;


#define ERR_T_UINT32		56  /*(0 .. 4294967295)*/
flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode);

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal);

#define ERR_UPER_ENCODE_T_UINT32		57  /**/
#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT32		58  /**/
flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Runtime_Error --------------------------------------------*/

typedef enum {
    T_Runtime_Error_NONE,
    T_Runtime_Error_noerror_PRESENT,
    T_Runtime_Error_encodeerror_PRESENT,
    T_Runtime_Error_decodeerror_PRESENT
} asn1SccT_Runtime_Error_selection;

typedef union {
    asn1SccT_UInt32 noerror;
    asn1SccT_Int32 encodeerror;
    asn1SccT_Int32 decodeerror;
} asn1SccT_Runtime_Error_unchecked_union;

typedef struct {
    asn1SccT_Runtime_Error_selection kind;

    asn1SccT_Runtime_Error_unchecked_union u;
} asn1SccT_Runtime_Error;

#define ERR_T_RUNTIME_ERROR		111  /**/
#define ERR_T_RUNTIME_ERROR_NOERROR_2		86  /**/
#define ERR_T_RUNTIME_ERROR_ENCODEERROR_2		96  /**/
#define ERR_T_RUNTIME_ERROR_DECODEERROR_2		106  /**/
flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode);

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal);

#define ERR_UPER_ENCODE_T_RUNTIME_ERROR		112  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_NOERROR_2		87  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		97  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		107  /**/
#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ENCODING        34

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_RUNTIME_ERROR		113  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_NOERROR_2		88  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		98  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		108  /**/
flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int8;


#define ERR_T_INT8		61  /*(-128 .. 127)*/
flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode);

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal);

#define ERR_UPER_ENCODE_T_INT8		62  /**/
#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT8		63  /**/
flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt8;


#define ERR_T_UINT8		66  /*(0 .. 255)*/
flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode);

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal);

#define ERR_UPER_ENCODE_T_UINT8		67  /**/
#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT8		68  /**/
flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccT_Boolean;


#define ERR_T_BOOLEAN		71  /**/
flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode);

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal);

#define ERR_UPER_ENCODE_T_BOOLEAN		72  /**/
#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_BOOLEAN		73  /**/
flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Null_Record --------------------------------------------*/
typedef struct {

} asn1SccT_Null_Record;

#define ERR_T_NULL_RECORD		76  /**/
flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode);

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ENCODING        0

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccPID_Range;


#define ERR_PID_RANGE		116  /*(0..3)*/
flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode);

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal);

#define ERR_UPER_ENCODE_PID_RANGE		117  /**/
#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID_RANGE		118  /**/
flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    PID_actuator = 0,
    PID_controller = 1,
    PID_environ = 2,
    PID_env = 3
} asn1SccPID;

// please use the following macros to avoid breaking code.
#define asn1SccPID_actuator PID_actuator
#define asn1SccPID_controller PID_controller
#define asn1SccPID_environ PID_environ
#define asn1SccPID_env PID_env

#define ERR_PID		121  /*actuator | controller | environ | env*/
flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode);

void asn1SccPID_Initialize(asn1SccPID* pVal);

#define ERR_UPER_ENCODE_PID		122  /**/
#define asn1SccPID_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID		123  /**/
flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
