name: Workflow
on: [pull_request]

jobs:
  check:
    runs-on: ghcr.io/n7space/taste-dev-env:feature-tmc-80-docker-image
    name: Check
    steps:    

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Functional check
      run: make check

    - name: Style check
      run: make check-format
