name: Workflow
on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup
    steps:
    - name: pytest
      run: pip3 install pytest

    - name: opengeode
      run: pip3 install opengeode

    - name: black
      run: pip3 install black

  check:
    runs-on: ubuntu-latest
    name: Check
    needs: setup
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Functional check
      run: make check

    - name: Style check
      run: make check-format
